services:
  gateway:
    restart: always
    build:
      context: ./gateway_service
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - auth_service
      - user_service

  auth_service:
    restart: always
    build:
      context: ./auth_service
      dockerfile: Dockerfile
    ports:
      - "8081:8181"
    depends_on: 
      - auth_postgres
  
  auth_postgres:
    image: postgres:17-alpine
    container_name: auth_db
    restart: always
    ports:
      - "15432:5432"
    env_file:
      - ./auth_service/.env
    environment:
      POSTGRES_USER: ${PG_USERNAME}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DATABASE}
    volumes:
      - ./postgres_data:/var/lib/postgresql/data 

  user_service:
    restart: always
    build:
      context: ./user_service
      dockerfile: Dockerfile
    ports:
      - "8082:8282"
    depends_on: 
      - auth_postgres
  
  user_postgres:
    image: postgres:17-alpine
    container_name: user_db
    restart: always
    ports:
      - "25432:5432"
    env_file:
      - ./user_service/.env
    environment:
      POSTGRES_USER: ${PG_USERNAME}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DATABASE} 
    volumes:
      - ./postgres_data:/var/lib/postgresql/data 

volumes:
  auth_postgres_data:
  user_postgres_data: