services:
  gateway:
    restart: always
    build:
      context: ./gateway_service
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - auth_service
      - user_service

  auth_service:
    restart: always
    build:
      context: ./auth_service
      dockerfile: Dockerfile
    ports:
      - "8081:8181"
    depends_on: 
      - auth_postgres
  
  auth_postgres:
    image: postgres:17-alpine
    container_name: auth_db
    restart: always
    ports:
      - "5430:5432"
    # env_file:
    #   - ./auth_service/.env
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: auth_db
      # POSTGRES_USER: ${PG_USERNAME}
      # POSTGRES_PASSWORD: ${PG_PASSWORD}
      # POSTGRES_DB: ${PG_DATABASE}
    volumes:
      - ./auth_postgres_data:/var/lib/postgresql/data 

  user_service:
    restart: always
    build:
      context: ./user_service
      dockerfile: Dockerfile
    ports:
      - "8082:8282"
    depends_on: 
      - user_postgres
  
  user_postgres:
    image: postgres:17-alpine
    container_name: user_db
    restart: always
    ports:
      - "5431:5432"
    # env_file:
    #   - ./user_service/.env
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: user_db
      # POSTGRES_USER: ${PG_USERNAME}
      # POSTGRES_PASSWORD: ${PG_PASSWORD}
      # POSTGRES_DB: ${PG_DATABASE} 
    volumes:
      - ./user_postgres_data:/var/lib/postgresql/data 

volumes:
  auth_postgres_data:
    driver: local
  user_postgres_data:
    driver: local