services:
  pgdb_user:
    image: postgres:alpine
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    ports:
      - "5432:5432"
    volumes:
      - pgdb_user_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d db"]
      interval: 5s
      timeout: 5s
      retries: 10
  
  app:
    container_name: app
    depends_on:
      pgdb_user:
        condition: service_healthy
    restart: on-failure
    build:
      context: .
      dockerfile: user_service/Dockerfile
    ports:
      - "8080:8080"

volumes:
  pgdb_user_data: