services:
  pgdb_user:
    image: postgres:alpine
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    networks:
      - backend
    volumes:
      - ./pgdb_user_data/postgresql/data:/var/lib/postgresql/data
      # - pgdb_user_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d db"]
      interval: 5s
      timeout: 5s
      retries: 10
  
  monolit_app:
    container_name: monolit_app
    depends_on:
      pgdb_user:
        condition: service_healthy
    restart: on-failure
    build:
      context: .
      dockerfile: docker/monolit/Dockerfile
    networks:
      - backend
      - frontend
  
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports: 
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - monolit_app
    networks:
      - frontend
    restart: unless-stopped

# volumes:
#   pgdb_user_data:

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge